### PR TITLE
fix: allow running as root to inject chaos

### LINKED ISSUE #520: Chaos injection requires root which is no longer permitted
The network and stress chaos injection requires root: https://github.com/search?q=repo%3Azeebe-io%2Fzeebe-chaos%20runAsUser&type=code

This is no longer allowed and we will need to fix it on our side so that QA works again: https://camunda.slack.com/archives/CT702EPFH/p1712147652179179

### PR DESCRIPTION
**Pull request by oleschoenburg**
Closes #520

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I'm still getting errors in testbench. Can't reproduce locally though.

```
panic: command terminated with exit code 100
[signal SIGSEGV: segmentation violation code=0xc000e54d70 addr=0x4f869b pc=0xc1c3f2]

goroutine 67 [running]:
github.com/zeebe-io/zeebe-chaos/go-chaos/cmd.ensureNoError(...)
	/home/ls/Source/github.com/zeebe-io/zeebe-chaos/go-chaos/cmd/disconnect.go:24
github.com/zeebe-io/zeebe-chaos/go-chaos/cmd.AddStressCmd.func1(0xc0008fab00?, {0x19d8cab?, 0x4?, 0x19d8b63?})
	/home/ls/Source/github.com/zeebe-io/zeebe-chaos/go-chaos/cmd/stress.go:55 +0x34b
github.com/spf13/cobra.(*Command).execute(0xc0008fc000, {0xc00183cf30, 0x9, 0x9})
	/home/ls/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000455b00)
	/home/ls/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/home/ls/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1048
github.com/zeebe-io/zeebe-chaos/go-chaos/cmd.runZbChaosCommand({0xc001bd00e0, 0xb, 0xe}, {0x1c743e0?, 0xc000521dc0})
	/home/ls/Source/github.com/zeebe-io/zeebe-chaos/go-chaos/cmd/worker.go:98 +0xf8
github.com/zeebe-io/zeebe-chaos/go-chaos/worker.HandleZbChaosJob({0x1c6ac10, 0xc000270120}, {0xc0003888f0}, 0x1afe550)
	/home/ls/Source/github.com/zeebe-io/zeebe-chaos/go-chaos/worker/chaos_worker.go:107 +0x513
github.com/zeebe-io/zeebe-chaos/go-chaos/cmd.handleZbChaosJob({0x1c6ac10?, 0xc000270120?}, {0x0?})
	/home/ls/Source/github.com/zeebe-io/zeebe-chaos/go-chaos/cmd/worker.go:91 +0x25
github.com/camunda/zeebe/clients/go/v8/pkg/worker.(*jobDispatcher).run.func2()
	/home/ls/go/pkg/mod/github.com/camunda/zeebe/clients/go/v8@v8.5.0/pkg/worker/jobDispatcher.go:54 +0xc9
created by github.com/camunda/zeebe/clients/go/v8/pkg/worker.(*jobDispatcher).run in goroutine 15
	/home/ls/go/pkg/mod/github.com/camunda/zeebe/clients/go/v8@v8.5.0/pkg/worker/jobDispatcher.go:45 +0x149
```

**Comment by oleschoenburg** [comment]
One idea I have to overcome this is to attach ephemeral debug containers that have the necessary tools installed.

**Comment by Zelldon** [comment]
Was also thinking a out this but thought might not work with permissions?


Another one I was thinking whether we could leverage ebpf

**Comment by oleschoenburg** [comment]
I think I got the permissions working:
```
ls@camunda:~/Source/github.com/zeebe-io/zeebe-chaos/go-chaos$ kubectl logs zeebe-2 -c debug-tvjfnw

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.7 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1690 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [2124 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1081 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1357 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [61.3 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [2173 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1969 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [80.9 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [33.3 kB]
Fetched 30.9 MB in 4s (7275 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
```

**Comment by Zelldon** [comment]
@oleschoenburg was it working? Can we get it merged?

**Comment by oleschoenburg** [comment]
@Zelldon I have something ready locally that seems to work more or less but now the scaling test doesn't work anymore ?! I need to test this manually a bit more.

File: go-chaos/internal/network.go [hunk 1]
```diff
@@ -15,150 +15,41 @@
...
-
-	_, err = c.Clientset.AppsV1().Deployments(c.GetCurrentNamespace()).Patch(context.TODO(), deployment.Name, types.StrategicMergePatchType, patch, metav1.PatchOptions{})
-	return err
-}
-
 func MakeIpUnreachableForPod(k8Client K8Client, podIp string, podName string) error {
-	// We try to reduce the system output in order to not break the execution. There is a limit for the sout for exec,
-	// for more details see remotecommand.StreamOptions
-
-	// the -qq flag makes the tool less noisy, remove it to get more output
```
Comment (Zelldon) [inline go-chaos/internal/network.go:94]: ❓ Do you have seen the comments? I think this still applies?

File: go-chaos/internal/network.go [hunk 2]
```diff
@@ -15,150 +15,41 @@
...
-	err = k8Client.ExecuteCmdOnPod([]string{"ip", "route", "replace", "unreachable", podIp}, podName)
-	if err != nil {
-		return err
-	}
-
-	return nil
+	cmd := []string{"ip", "route", "replace", "unreachable", podIp}
+	cmdWithSetup := []string{"sh", "-c", "apt update && apt install -y iproute2 && " + strings.Join(cmd, " ")}
+	var containerName string
+	if strings.Contains(podName, "gateway") {
```
Comment (Zelldon) [inline go-chaos/internal/network.go:25]: Is this to work with SaaS/SM?

Comment (Zelldon) [reply go-chaos/internal/network.go:25]: We have also functions to get the right pod name.

File: go-chaos/internal/pods.go [hunk 3]
```diff
@@ -302,6 +303,35 @@ func (c K8Client) createPortForwardUrl(names []string) *url.URL {
...
 }
 
+func (c K8Client) ExecuteCommandViaDebugContainer(podName string, containerName string, debugImage string, cmd []string) error {
+	pod, err := c.Clientset.CoreV1().Pods(c.GetCurrentNamespace()).Get(context.TODO(), podName, metav1.GetOptions{})
+	if err != nil {
+		return err
+	}
+	name := "debug-" + rand.String(6)
+	debugContainer := v1.EphemeralContainer{
+		EphemeralContainerCommon: v1.EphemeralContainerCommon{
```
Comment (Zelldon) [inline go-chaos/internal/pods.go:313]: Hm and this works? 🤔 Interesting. Could we use the same for zdb? I was always wondering why it didn't worked to access the data from ephemeral container. https://github.com/Zelldon/zdb/issues/332

File: go-chaos/internal/pods.go [hunk 4]
```diff
@@ -302,6 +303,35 @@ func (c K8Client) createPortForwardUrl(names []string) *url.URL {
 	return portForwardCreateURL
 }
 
+func (c K8Client) ExecuteCommandViaDebugContainer(podName string, containerName string, debugImage string, cmd []string) error {
```
Comment (Zelldon) [inline go-chaos/internal/pods.go:306]: Did you verified whether it was for real disrupting the network? Or maybe it was just silently failing? 🤔 So for example did the brokers showed that they can't connect?

**Review by Zelldon — COMMENTED** [review]
Thanks @oleschoenburg if this for real works this would be great! Could you check my comments?

File: go-chaos/internal/network.go (hunk 1 above)
Comment (oleschoenburg) [reply go-chaos/internal/network.go:94]: We could still use `-qq` but it doesn't hurt to have more output. We are not capturing stdout anymore, it's only visible through the container logs (`kubectl logs ...`)

File: go-chaos/internal/network.go (hunk 2 above)
Comment (oleschoenburg) [reply go-chaos/internal/network.go:25]: This is to attach to the correct container, both on SaaS and self-managed. We already have the right `podName` here. Do you mean we have helper functions to get the right _container_ name?

File: go-chaos/internal/pods.go (hunk 3 above)
Comment (oleschoenburg) [reply go-chaos/internal/pods.go:313]: Yeah, I don't know what's going wrong in https://github.com/Zelldon/zdb/issues/332 but the debug container here has enough permissions to install the stress tool and run it at least.

File: go-chaos/internal/pods.go (hunk 4 above)
Comment (oleschoenburg) [reply go-chaos/internal/pods.go:306]: Not yet! That's one of the things I still have to do :-/

File: go-chaos/internal/network.go (hunk 2 above)
Comment (Zelldon) [reply go-chaos/internal/network.go:25]: The pod name you use is actually only correct in SaaS in SM it is different but not sure whether you use the pod name here anyhow.

File: go-chaos/internal/pods.go (hunk 4 above)
Comment (oleschoenburg) [reply go-chaos/internal/pods.go:306]: I've tested it now with a SaaS cluster :tada: 

```
$ zbchaos --namespace 8fe648b5-1137-4d6a-af0d-be8b467fd67e-zeebe disconnect brokers --broker2NodeId 2 --broker1NodeId 1 --verbose
Flags: {1 LEADER -1  10  msg false 1 LEADER 1 2 LEADER 2 1 1713797975967 false false true false false 30 false -1 benchmark 30  8fe648b5-1137-4d6a-af0d-be8b467fd67e-zeebe 1 1 benchmark-task 0 0 0 1 -1 true}
Connecting to 8fe648b5-1137-4d6a-af0d-be8b467fd67e-zeebe
Running experiment in SaaS environment.
Patched statefulset
Port forward to zeebe-gateway-5489b4cdcf-ptfl9
Successfully created port forwarding tunnel from 46535 (local) to 26500 (remote)
Found Broker zeebe-1 with node id 1.
Found Broker zeebe-2 with node id 2.
Debug container debug-lvccl4 is running command [sh -c apt update && apt install -y iproute2 && ip route replace unreachable 10.64.73.38]
Disconnect zeebe-1 from zeebe-2
Debug container debug-658dxp is running command [sh -c apt update && apt install -y iproute2 && ip route replace unreachable 10.64.53.29]
Disconnect zeebe-2 from zeebe-1

$ zbchaos --namespace 8fe648b5-1137-4d6a-af0d-be8b467fd67e-zeebe connect brokers --verbose
Flags: {1 LEADER -1  10  msg false 1 LEADER -1 2 LEADER -1 1 1713798188959 false false true false false 30 false -1 benchmark 30  8fe648b5-1137-4d6a-af0d-be8b467fd67e-zeebe 1 1 benchmark-task 0 0 0 1 -1 true}
Connecting to 8fe648b5-1137-4d6a-af0d-be8b467fd67e-zeebe
Running experiment in SaaS environment.
Debug container debug-cv444p is running command [sh -c apt update && apt install -y iproute2 && ip route del $(ip route | grep -m 1 unreachable)]
Connected zeebe-0 again, removed unreachable routes.
Debug container debug-zg45fm is running command [sh -c apt update && apt install -y iproute2 && ip route del $(ip route | grep -m 1 unreachable)]
Connected zeebe-1 again, removed unreachable routes.
Debug container debug-tm9pdj is running command [sh -c apt update && apt install -y iproute2 && ip route del $(ip route | grep -m 1 unreachable)]
Connected zeebe-2 again, removed unreachable routes.
```

image
image

File: go-chaos/internal/network.go (hunk 2 above)
Comment (oleschoenburg) [reply go-chaos/internal/network.go:25]: This code here uses the pod name to figure out the correct _container_ name. If the pod name includes gateway, we assume that the container name is `zeebe-gateway`, otherwise we expect it to be `zeebe`. I think this should work in both SaaS and SM, right?

**Review by Zelldon — APPROVED** [review]
Really great stuff @oleschoenburg ❤️ thanks for your efforts!
