### PR TITLE
Saas detection error handling

### LINKED ISSUE #488: Detection of SaaS vs SM environment incorrectly fallback to SM
Observed the following error when running chaos tests against our SaaS cluster
```
Failed to retrieve SaaS CRD, fallback to self-managed mode. Get "https://34.79.82.85/apis/cloud.camunda.io/v1alpha1/zeebeclusters/e8196081-1341-4b05-a7fb-b3c7dcf8f646": dial tcp 34.79.82.85:443: i/o timeout"
```

As a result "workers" for a test were deployed using SM configuration which uses a different service name for the gateways. The test failed because the workers cannot talk to the Zeebe gateway because of the incorrect service neame.

** Expected behavior **
 
The environment is detected correctly. 
Timeouts should not considered as a valid response to determine the environment. It should be retried.

### PR DESCRIPTION
**Pull request by Zelldon**
Paired with @oleschoenburg on this:

 * We agreed on to "simply" pass the error to the front, to the respective commands so they can either fail or do what ever
 * For errors indicating resource not-found we decided to return false, and use SM setting (as we expect this CRD not in the SM env)
 * We wrote some more tests for the error handling
 * I had to refactor a bit the client creation, so we test the right things here

closes #488 
closes #490

### CODE REVIEW

File: go-chaos/internal/k8helper.go [hunk 1]
```diff
@@ -49,6 +49,26 @@ func CreateK8Client(kubeConfigPath string, namespace string) (K8Client, error) {
...
 
 func createK8Client(settings KubernetesSettings) (K8Client, error) {
+	client, err := internalCreateClient(settings)
+	if err != nil {
+		return client, err
+	}
+
+	client.SaaSEnv, err = client.isSaaSEnvironment()
+	if err != nil {
+		return client, err
```
Comment (oleschoenburg) [inline go-chaos/internal/k8helper.go:59]: :upside_down_face: Super nitpicky but I think we are not supposed to return the client in this case? 

```suggestion
		return nil, err
```

Comment (Zelldon) [reply go-chaos/internal/k8helper.go]: Makes sense thanks 👍🏼

**Comment by Zelldon** [comment]
```
go build -o zbchaos main.go
# github.com/zeebe-io/zeebe-chaos/go-chaos/internal
Error: internal/k8helper.go:5[9](https://github.com/zeebe-io/zeebe-chaos/actions/runs/7843937019/job/21405291067#step:7:10):[10](https://github.com/zeebe-io/zeebe-chaos/actions/runs/7843937019/job/21405291067#step:7:11): cannot use nil as K8Client value in return statement
make: *** [Makefile:11: build] Error 1
Error: Process completed with exit code 2.
```

😿

**Comment by Zelldon** [comment]
@oleschoenburg I would remove the last commit, we would either have to return K8Client{} or simply the client obj we had before. wdyt?

**Comment by oleschoenburg** [comment]
Ah how annoying. Yeah, just drop the last commit.
